[meta]
version = "0.1.0"

[project]
name = "xlattice_go"
package = "xlattice_go"
main_lang = "go"
version = "0.4.19"
version_date = "2017-11-10"
author = "Jim Dixon"
author_email = "jddixon@gmail.com"
copyright = "2013-2017"
description = "Go implementation of XLattice communications package"
dev_status = "alpha"
license = "mit"
relpath = "go/src/github.com/jddixon/xlattice_go"
state = "shared"
url = "https://jddixon.github.io/xlattice_go"

[go]
cmds = [ "ssh2pkcs8",]
